"""users table

Revision ID: dcfb7558705b
Revises: 
Create Date: 2018-07-21 20:13:37.724676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfb7558705b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_desc', sa.String(length=100), nullable=True),
    sa.Column('long_desc', sa.String(length=5000), nullable=True),
    sa.Column('notification_by', sa.Integer(), nullable=True),
    sa.Column('active', sa.SMALLINT(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('hashed_password', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=90), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('github', sa.String(length=50), nullable=True),
    sa.Column('kaggle', sa.String(length=50), nullable=True),
    sa.Column('linkedin', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.SMALLINT(), nullable=True),
    sa.Column('active', sa.SMALLINT(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('notifications')
    # ### end Alembic commands ###
